[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore ./testCICD/testCICD/testCICD.csproj",
  "dotnet publish ./testCICD/testCICD/testCICD.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/testCICD.dll --urls=http://0.0.0.0:$PORT"
